# docker-compose.yaml  5
version: '1'

services:
  nginx-react:
    image: reactapp:latest
    container_name: myreactapptest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production